const SITES = {
  tech: {
    name: "tech.com.pk",
    baseUrl: "https://tech.com.pk",
    searchUrl: "https://tech.com.pk/?s={query}&post_type=product",
    productUrlPattern: /\/[^/]+-p\.\d+\.aspx$/i,
    selectors: {
      searchResults: ".productCard, .product-item, .product-card, .product-box",
      productLink: "a.productTitle, a[href*=\"/product/\"]",
      name: "h1.product-title, .productTitle, .productTitle a, h1.product-title, .product-title",
      price: ".price, .product-price, .special-price, .price-box .price, .product-price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".product-description, .description, .product-details .description, .tab-content.description",
      shortDescription: ".short-description, .product-short-description",
      specsTable: ".specifications-table, .product-specifications table, .product-attributes table, .data-table",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications-list, .product-specs dl, .attributes-list",
      specItem: "dt, .spec-label",
      specValueDD: "dd, .spec-value",
      mainImage: ".product-image img, .product-gallery img, .main-image img, .productCard img",
      galleryImages: ".product-gallery img, .product-images img, .gallery img",
      specsTab: "#specification, #specifications, .tab-specification",
      breadcrumbs: ".breadcrumb, .breadcrumbs, .product-breadcrumb",
      availability: ".stock, .availability, .in-stock, .out-of-stock",
      brand: ".brand, .product-brand, .manufacturer",
      sku: ".sku, .product-sku, .product-code",
    },
    searchSelectors: {
      input: "input[name=\"q\"], input[name=\"search\"], #search, .search-input",
      button: "button[type=\"submit\"], .search-btn, .search-button",
      results: ".search-results, .products-grid, .product-listing",
    },
  },

  techlad: {
    name: "techlad.pk",
    baseUrl: "https://techlad.pk",
    searchUrl: "https://techlad.pk/?s={query}&post_type=product",
    productUrlPattern: /\/product\/[\w-]+/,
    selectors: {
      searchResults: ".product-item, .product-grid-item, .product-card",
      productLink: "a[href*=\".aspx\"]",
      name: "h1.product-title, h1.product-name, .product-title",
      price: ".price, .product-price, .special-price, .price-box .price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".product-description, .description, .product-details .description, .tab-content.description",
      shortDescription: ".short-description, .product-short-description",
      specsTable: ".specifications-table, .product-specifications table, .product-attributes table, .data-table",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications-list, .product-specs dl, .attributes-list",
      specItem: "dt, .spec-label",
      specValueDD: "dd, .spec-value",
      mainImage: ".product-image img, .product-gallery img, .main-image img",
      galleryImages: ".product-gallery img, .product-images img, .gallery img",
      specsTab: "#specification, #specifications, .tab-specification",
      breadcrumbs: ".breadcrumb, .breadcrumbs, .product-breadcrumb",
      availability: ".stock, .availability, .in-stock, .out-of-stock",
      brand: ".brand, .product-brand, .manufacturer",
      sku: ".sku, .product-sku, .product-code",
    },
    searchSelectors: {
      input: "input[name=\"q\"], input[name=\"search\"], #search, .search-input",
      button: "button[type=\"submit\"], .search-btn, .search-button",
      results: ".search-results, .products-grid, .product-listing",
    },
  },

  zahcomputers: {
    name: "zahcomputers.pk",
    baseUrl: "https://zahcomputers.pk",
    searchUrl: "https://zahcomputers.pk/?s={query}&post_type=product",
    productUrlPattern: /\/product\/[\w-]+/,
    selectors: {
      searchResults: ".product-item, .product-grid-item, .product-card",
      productLink: "a[href*=\"/product/\"]",
      name: "h1.product-title, h1.product-name, .product-title",
      price: ".price, .product-price, .special-price, .price-box .price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".product-description, .description, .product-details .description, .tab-content.description",
      shortDescription: ".short-description, .product-short-description",
      specsTable: ".specifications-table, .product-specifications table, .product-attributes table, .data-table",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications-list, .product-specs dl, .attributes-list",
      specItem: "dt, .spec-label",
      specValueDD: "dd, .spec-value",
      mainImage: ".product-image img, .product-gallery img, .main-image img",
      galleryImages: ".product-gallery img, .product-images img, .gallery img",
      specsTab: "#specification, #specifications, .tab-specification",
      breadcrumbs: ".breadcrumb, .breadcrumbs, .product-breadcrumb",
      availability: ".stock, .availability, .in-stock, .out-of-stock",
      brand: ".brand, .product-brand, .manufacturer",
      sku: ".sku, .product-sku, .product-code",
    },
    searchSelectors: {
      input: "input[name=\"q\"], input[name=\"search\"], #search, .search-input",
      button: "button[type=\"submit\"], .search-btn, .search-button",
      results: ".search-results, .products-grid, .product-listing",
    },
  },

  // UNVERIFIED (czone, techmatched, zestrogaming below): I confirmed these
  // three sites are live, but couldn't pull a real product page to check
  // actual CSS classes, so these reuse the generic template from techlad/
  // zahcomputers above. Before running at volume: open one product page on
  // each, inspect-element the price and title, and confirm the selectors
  // below actually match. If they don't, that site will just silently
  // return nothing instead of erroring — worth testing on 1 product first.
  czone: {
    name: "czone.com.pk",
    baseUrl: "https://www.czone.com.pk",
    searchUrl: "https://www.czone.com.pk/search.aspx?search={query}",
    searchUrls: [
      "https://www.czone.com.pk/search.aspx?search={query}",
      "https://www.czone.com.pk/?s={query}&post_type=product"
    ],
    productUrlPattern: /\\/[^/]+-p\\.\\d+\\.aspx$/i,
    selectors: {
      searchResults: ".search-results, .product-list, .products",
      productLink: "a[href*=\".aspx\"]",
      name: "h1, .product-title, .product-name",
      price: ".price, .product-price, .special-price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".description, .product-description, .product-details",
      shortDescription: ".short-description, .product-description",
      specsTable: "table, .specifications, .product-specifications",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications, .product-specs",
      specItem: "dt, .label",
      specValueDD: "dd, .value",
      mainImage: "img",
      galleryImages: "img",
      specsTab: "",
      breadcrumbs: ".breadcrumb, .breadcrumbs",
      availability: ".stock, .availability",
      brand: ".brand, .manufacturer",
      sku: ".sku, .product-code"
    },
    searchSelectors: {
      results: ".search-results, .product-list, .products"
    }
  },

  techmatched: {
    name: "techmatched.pk",
    baseUrl: "https://techmatched.pk",
    searchUrl: "https://techmatched.pk/?s={query}&post_type=product",
    productUrlPattern: /\/product\/[\w-]+/,
    selectors: {
      searchResults: ".product-item, .product-grid-item, .product-card",
      productLink: "a[href*=\"/product/\"]",
      name: "h1.product-title, h1.product-name, .product-title",
      price: ".price, .product-price, .special-price, .price-box .price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".product-description, .description, .product-details .description, .tab-content.description",
      shortDescription: ".short-description, .product-short-description",
      specsTable: ".specifications-table, .product-specifications table, .product-attributes table, .data-table",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications-list, .product-specs dl, .attributes-list",
      specItem: "dt, .spec-label",
      specValueDD: "dd, .spec-value",
      mainImage: ".product-image img, .product-gallery img, .main-image img",
      galleryImages: ".product-gallery img, .product-images img, .gallery img",
      specsTab: "#specification, #specifications, .tab-specification",
      breadcrumbs: ".breadcrumb, .breadcrumbs, .product-breadcrumb",
      availability: ".stock, .availability, .in-stock, .out-of-stock",
      brand: ".brand, .product-brand, .manufacturer",
      sku: ".sku, .product-sku, .product-code",
    },
    searchSelectors: {
      input: "input[name=\"q\"], input[name=\"search\"], #search, .search-input",
      button: "button[type=\"submit\"], .search-btn, .search-button",
      results: ".search-results, .products-grid, .product-listing",
    },
  },

  // The ZestrogamingScraper class assumes zestrogaming.pk — the real
  // domain is zestrogaming.com. Fixed here.
  zestrogaming: {
    name: "zestrogaming.com",
    baseUrl: "https://zestrogaming.com",
    searchUrl: "https://zestrogaming.com/?s={query}&post_type=product",
    productUrlPattern: /\/product\/[\w-]+/,
    selectors: {
      searchResults: ".product-item, .product-grid-item, .product-card",
      productLink: "a[href*=\"/product/\"]",
      name: "h1.product-title, h1.product-name, .product-title",
      price: ".price, .product-price, .special-price, .price-box .price",
      originalPrice: ".old-price, .price-old, .was-price",
      description: ".product-description, .description, .product-details .description, .tab-content.description",
      shortDescription: ".short-description, .product-short-description",
      specsTable: ".specifications-table, .product-specifications table, .product-attributes table, .data-table",
      specsRows: "tr",
      specLabel: "th, td:first-child",
      specValue: "td:last-child, td:nth-child(2)",
      specsList: ".specifications-list, .product-specs dl, .attributes-list",
      specItem: "dt, .spec-label",
      specValueDD: "dd, .spec-value",
      mainImage: ".product-image img, .product-gallery img, .main-image img",
      galleryImages: ".product-gallery img, .product-images img, .gallery img",
      specsTab: "#specification, #specifications, .tab-specification",
      breadcrumbs: ".breadcrumb, .breadcrumbs, .product-breadcrumb",
      availability: ".stock, .availability, .in-stock, .out-of-stock",
      brand: ".brand, .product-brand, .manufacturer",
      sku: ".sku, .product-sku, .product-code",
    },
    searchSelectors: {
      input: "input[name=\"q\"], input[name=\"search\"], #search, .search-input",
      button: "button[type=\"submit\"], .search-btn, .search-button",
      results: ".search-results, .products-grid, .product-listing",
    },
  },

  pclab: {
    name: "pclab.pk",
    baseUrl: "https://pclab.pk",
    searchUrl: "https://pclab.pk/?s={query}&post_type=product",
    productUrlPattern: /\/product\/[\w-]+/,
    selectors: {
      searchResults: ".product-item, .product-grid .item, .product-box",
      productLink: "a[href*=\"/product/\"]",
      name: "h1.product-title, h1.product_name, .product-name h1",
      price: ".price, .product-price .amount, .special-price",
      originalPrice: ".old-price, .price-old",
      description: ".product-description, .description .std, .product-desc",
      shortDescription: ".short-description, .short-desc",
      specsTable: ".product-attributes table, .specifications table, #product-attribute-specs-table",
      specsRows: "tr",
      specLabel: "th, td.label",
      specValue: "td.value, td:last-child",
      specsList: ".product-specs, .specifications",
      specItem: "dt, .label",
      specValueDD: "dd, .value",
      mainImage: ".product-image-gallery img, .gallery-placeholder img, .product-img-box img",
      galleryImages: ".product-image-thumbs img, .more-views img, .gallery img",
      specsTab: "#product_tabs_specification, #specifications, .tab-specs",
      breadcrumbs: ".breadcrumbs, .breadcrumb",
      availability: ".availability, .stock-status",
      brand: ".brand, .manufacturer",
      sku: ".sku, .product-sku",
    },
    searchSelectors: {
      input: "#search, input[name=\"q\"], .search-query",
      button: ".search-button, button[type=\"submit\"]",
      results: ".products-grid, .products-list",
    },
  },
};

const COMMON_SELECTORS = {
  name: ["h1.product-title", "h1.product-name", ".product-title h1", ".product-name h1", "h1.product_name", ".product-title", ".product-name"],
  price: [".price", ".product-price", ".special-price", ".product-price .amount", ".special-price .amount"],
  originalPrice: [".old-price", ".was-price", ".price-old", ".regular-price"],
  description: [".product-description", ".description", ".product-desc", ".description .std", ".product-details"],
  specsTable: [".specifications table", ".product-specifications table", ".product-attributes table", "#product-attribute-specs-table", ".product-attributes-table"],
  specsList: [".specifications-list", ".product-specs", ".specifications", ".product-specs dl", ".attributes-list"],
  mainImage: [".product-image img", ".product-image-gallery img", ".gallery-placeholder img", ".product-img-box img", ".product-image-gallery img", ".featured-image img"],
  galleryImages: [".product-gallery img", ".product-images img", ".product-image-thumbs img", ".more-views img", ".gallery img"],
  specsTab: ["#specifications", "#specification", ".tab-specification", "#product_tabs_specification", "#product_tabs_specifications"],
  breadcrumbs: [".breadcrumb", ".breadcrumbs", ".product-breadcrumb"],
  availability: [".stock", ".availability", ".stock-status", ".in-stock", ".out-of-stock"],
  brand: [".brand", ".brand-name", ".manufacturer", ".product-brand"],
  sku: [".sku", ".product-sku", ".product-code"],
};

module.exports = { SITES, COMMON_SELECTORS };
